FROM sbtscala/scala-sbt:eclipse-temurin-jammy-17.0.5_8_1.9.3_2.12.18 as sbt

# Copy source files
WORKDIR /src
COPY . .

CMD ["sbt", "-mem", "2048", "test"]

LABEL maintainer="Lubos Kozmon <contact@elkozmon.com>"