name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: sbt
    - name: Set sbt
      uses: sbt/setup-sbt@v1
    - name: Run tests
      run: sbt test
    - name: Upload dependency graph
      uses: scalacenter/sbt-dependency-submission@v3.1.0
